---
# tasks file for group
- name: GROUP | Managing groups...
  ansible.builtin.group:
    force:  "{{ item.force }}"
    gid:  "{{ item.gid | default(omit) }}"
    local:  "{{ item.local }}"
    name: "{{ item }}"
    non_unique: "{{ item.non_unique }}"
    state: "{{ item.state }}"
    system: "{{ item.system }}"
  with_items: "{{ group }}"
  tags: [ group,manage ]

